apiVersion: v2
name: main
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: '0.1.0'
dependencies:
  - name: n8n
    version: '0.1.0'
    repository: 'file://../_n8n'
    condition: n8n.enabled
  - name: pgo
    version: '0.1.0'
    repository: 'file://../_pgo'
    condition: pgo.enabled
  - name: postgresql
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 24.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
