{{- if .Values.webhook.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "_.fullname" . }}-webhook
  labels:
    {{- include "_.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "_.fullname" . }}
  minReplicas: {{ .Values.webhook.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.webhook.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.webhook.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.webhook.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.webhook.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.webhook.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
