volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:

networks:
  chwf:

x-n8n: &service-n8n
  build:
    context: .
    dockerfile: dockerfiles/n8n.Dockerfile
  environment:
    DB_TYPE: postgresdb
    DB_POSTGRESDB_HOST: postgres
    DB_POSTGRESDB_USER: ${POSTGRES_USER}
    DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
    N8N_DIAGNOSTICS_ENABLED: "false"
    N8N_PERSONALIZATION_ENABLED: "false"
    N8N_TEMPLATES_ENABLED: "false"
    N8N_AI_ENABLED: "false"
    N8N_HIRING_BANNER_ENABLED: "false"
    # When a key has no value, it passes the variable from the host machine
    N8N_ENCRYPTION_KEY:
    N8N_USER_MANAGEMENT_JWT_SECRET:
    N8N_HIDE_USAGE_PAGE: "true"
    N8N_HIDE_ACTIVATION_ALERT: "true"
    N8N_HIDE_HIDE_GITHUB_STAR_BUTTON: "true"
    N8N_DISABLED_MODULES: "external-secrets,mcp,chat-hub"
    OLLAMA_HOST: ${OLLAMA_HOST:-ollama:11434}
    N8N_PORT: "5678"
    NODE_ENV: production
    EXTERNAL_HOOK_FILES: /home/node/.n8n/external-hooks/oidc.js:/home/node/.n8n/external-hooks/test.js
    # Trust proxy for rate limiting
    N8N_TRUST_PROXY: "true"
    # OIDC Configuration
    # OIDC_ISSUER_URL: http://keycloak:8080/realms/starter
    OIDC_AUTHORIZATION_ENDPOINT: http://localhost:8080/realms/starter/protocol/openid-connect/auth
    OIDC_TOKEN_ENDPOINT: http://keycloak:8080/realms/starter/protocol/openid-connect/token
    OIDC_USERINFO_ENDPOINT: http://keycloak:8080/realms/starter/protocol/openid-connect/userinfo
    OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
    OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
    OIDC_REDIRECT_URI: http://localhost:5678/rest/auth/oidc/callback
    OIDC_ROLES_CLAIM: client_roles
    N8N_PROXY_HOPS: "1"
    # Frontend hooks for OIDC login customization
    EXTERNAL_FRONTEND_HOOKS_URLS: /assets/oidc-frontend-hook.js
    # Exclude /auth/* routes
    N8N_ADDITIONAL_NON_UI_ROUTES: auth
  networks: [chwf]

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ollama_storage:/root/.ollama
  networks: [chwf]

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  container_name: ollama-pull-llama
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  environment:
    OLLAMA_HOST: ollama:11434
  command:
    - "-c"
    - "sleep 3; ollama pull llama3.2"
  networks: [chwf]

services:
  postgres:
    platform: linux/amd64
    container_name: postgres
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks: [chwf]

  keycloak:
    platform: linux/amd64
    container_name: keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    command:
    - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_HTTP_PORT: 8080
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KEYCLOAK_ADMIN:
      KEYCLOAK_ADMIN_PASSWORD:
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.scripts=enabled
    ports:
    - 8080:8080
    - 8443:8443
    networks: [chwf]
    depends_on:
    - postgres


  keycloak-provision:
    platform: linux/amd64
    container_name: keycloak-provision
    build:
      context: ./keycloak-provision
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      MASTER_ADMIN: ${KEYCLOAK_ADMIN}
      MASTER_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      AUTH_REALM_NAME: starter
      AUTH_CLIENT_ID: ${OIDC_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
    networks: [chwf]
    depends_on:
      keycloak:
        condition: service_started

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
    - "-c"
    - |
      if [ -z "$(n8n list:workflow --onlyId)" ]; then
        n8n import:credentials --separate --input=/demo-data/credentials && \
        n8n import:workflow --separate --input=/demo-data/workflows
      else
        echo "Workflows exist, skipping import"
      fi

      ls -al /home/node/.n8n/nodes
      ls -al /community-nodes

      cd /home/node/.n8n/nodes
      rm -rf node_modules package-lock.json
      npm install /community-nodes

      ls -al /home/node/.n8n/nodes
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/demo-data:/demo-data
      - ../community-nodes:/community-nodes
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/demo-data:/demo-data
      - ../community-nodes:/community-nodes
      - ../external-hooks:/home/node/.n8n/external-hooks
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  qdrant:
    platform: linux/amd64
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks: [chwf]

  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-gpu-amd:
    profiles: ["gpu-amd"]
    <<: *service-ollama
    image: ollama/ollama:rocm
    devices:
      - "/dev/kfd"
      - "/dev/dri"

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu

  ollama-pull-llama-gpu-amd:
    profiles: [gpu-amd]
    <<: *init-ollama
    image: ollama/ollama:rocm
    depends_on:
     - ollama-gpu-amd
