{{- $secretName := printf "%s-%s" (include "_.fullname" .) "shared" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "_.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  {{- if $secret }}
  encryption-key: {{ index $secret.data "encryption-key" }}
  runners-auth-token: {{ index $secret.data "runners-auth-token" }}
  {{- else }}
  {{- $randPassword := randAlphaNum 32 }}
  encryption-key: {{ randAlphaNum 32 | b64enc | quote }}
  runners-auth-token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
