{{- $secretName := printf "%s-%s" (include "_.fullname" .) "redis" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "_.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  {{- if $secret }}
  redis-password: {{ index $secret.data "redis-password" }}
  {{- else }}
  {{- $randPassword := randAlphaNum 32 }}
  redis-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
