{{- if .Values.runner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "_.fullname" . }}-runner
  labels:
    {{- include "_.labels" . | nindent 4 }}
    app.kubernetes.io/component: runner
spec:
  type: {{ .Values.runner.service.type }}
  ports:
    - port: {{ .Values.runner.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "_.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: runner
{{- end }}
