{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "_.fullname" . }}-webhook
  labels:
    {{- include "_.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "_.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
{{- end }}
