{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "_.fullname" . }}-worker
  labels:
    {{- include "_.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "_.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}
